services:
  api:
    build: .
    entrypoint: ["/bin/sh", "-c", "exec npm run start"]
    environment:
      - PORT=6969
    ports:
      - 6969:6969
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - series_info
    env_file:
      - ./dev.env

  series_info:
    build: ./microservices/series-info-service
    entrypoint: ["/bin/sh", "-c", "exec npm run start"]
    environment:
      - PORT=6968
    ports:
      - 6968:6968
    volumes:
      - ./microservices/series-info-service:/app
      - /app/node_modules

    env_file:
      - ./dev.env

  extraction-service:
    build: ./microservices/extraction-service
    entrypoint: ["/bin/sh", "-c", "exec npm run start"]
    environment:
      - PORT=6967
    ports:
      - 6967:6967
    volumes:
      - ./microservices/extraction-service:/app
      - /app/node_modules

    env_file:
      - ./dev.env

  storage-service:
    build: ./microservices/storage-service
    entrypoint: ["/bin/sh", "-c", "exec npm run start"]
    environment:
      - PORT=6966
    ports:
      - 6966:6966
    volumes:
      - ./microservices/storage-service:/app
      - /app/node_modules
    env_file:
      - ./dev.env

  database-service:
    image: microservices/database-service
    entrypoint: ["/bin/sh", "-c", "exec npm run start"]
    environment:
      - PORT=6965
    ports:
      - 6965:6965
    volumes:
      - ./microservices/database-service/database.sqlite:/app/microservices/database-service/database.sqlite
      - /app/node_modules
    env_file:
      - ./dev.env