services:
  api:
    build: .
    entrypoint: ["/bin/sh", "-c", "exec npm run start"]
    environment:
      - PORT=6969
    ports:
      - 6969:6969
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - series_info
      - storage-service
    env_file:
      - ./production.env

  series_info:
    build: ./microservices/series-info-service
    entrypoint: ["/bin/sh", "-c", "exec npm run start"]
    environment:
      - PORT=6968
    ports:
      - 6968:6968
    volumes:
      - ./microservices/series-info-service:/app
      - /app/node_modules
    env_file:
      - ./docker.env

  storage-service:
    build: ./microservices/storage-service
    entrypoint: ["/bin/sh", "-c", "exec npm run start"]
    environment:
      - PORT=6966
    ports:
      - 6966:6966
    volumes:
      - ./microservices/storage-service:/app
      - /app/node_modules
    env_file:
      - ./production.env
